name: React-Native.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: rm -rf node_modules
      - run: rm -rf package-lock.json
      - run: npm install
      - run: npm install jest@latest
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true